apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql
  name: mysql
spec:
  containers:
  - image: mysql:8.0.33
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test
    - name: MYSQL_DATABASE
      value: myapps
    name: mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
