apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: employeemanagement
  name: employeemanagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanagement
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: employeemanagement
    spec:
      containers:
      - image: gagan2104/employeemanagement:{{ .Values.image.tag }}
        name: employeemanagement
        resources: {}
status: {}
